Commit to main

diff --git a/deployments/deploy_mysql.yaml b/deployments/deploy_mysql.yaml
--- a/deployments/deploy_mysql.yaml
+++ b/deployments/deploy_mysql.yaml
@@ -18,6 +18,21 @@ spec:
       nodeSelector:
         kubernetes.io/hostname: pinode01
       initContainers:
+      - name: init-iptables
+        image: ubuntu:latest
+        command:
+        - /bin/sh
+        - -c
+        - |
+          apt-get update && apt-get install -y iproute2 dnsutils
+          GLUETUN_IP=$(dig +short gluetun.default.svc.cluster.local)
+          if [ -z "$GLUETUN_IP" ]; then
+            echo "Failed to resolve gluetun service IP"
+            exit 1
+          fi
+          ip route add default via $GLUETUN_IP
+        securityContext:
+          privileged: true
       containers:
       - name: mysql
         image: bugbountytools/mysql:8.0
